# Generated by Django 3.2.9 on 2021-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='username',
            field=models.CharField(default=9, max_length=15),
            preserve_default=False,
        ),
    ]
